version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  api:
    image: node:alpine
    build: .
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  redis:
    image: redis:alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7

  rabbitmq:
    image: rabbitmq:3

  mongodb:
    image: mongo:latest